// Code generated by go-swagger; DO NOT EDIT.

package pet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// AddPetReader is a Reader for the AddPet structure.
type AddPetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddPetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 405:
		result := NewAddPetMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /pet] addPet", response, response.Code())
	}
}

// NewAddPetMethodNotAllowed creates a AddPetMethodNotAllowed with default headers values
func NewAddPetMethodNotAllowed() *AddPetMethodNotAllowed {
	return &AddPetMethodNotAllowed{}
}

/*
AddPetMethodNotAllowed describes a response with status code 405, with default header values.

Invalid input
*/
type AddPetMethodNotAllowed struct {
}

// IsSuccess returns true when this add pet method not allowed response has a 2xx status code
func (o *AddPetMethodNotAllowed) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this add pet method not allowed response has a 3xx status code
func (o *AddPetMethodNotAllowed) IsRedirect() bool {
	return false
}

// IsClientError returns true when this add pet method not allowed response has a 4xx status code
func (o *AddPetMethodNotAllowed) IsClientError() bool {
	return true
}

// IsServerError returns true when this add pet method not allowed response has a 5xx status code
func (o *AddPetMethodNotAllowed) IsServerError() bool {
	return false
}

// IsCode returns true when this add pet method not allowed response a status code equal to that given
func (o *AddPetMethodNotAllowed) IsCode(code int) bool {
	return code == 405
}

// Code gets the status code for the add pet method not allowed response
func (o *AddPetMethodNotAllowed) Code() int {
	return 405
}

func (o *AddPetMethodNotAllowed) Error() string {
	return fmt.Sprintf("[POST /pet][%d] addPetMethodNotAllowed", 405)
}

func (o *AddPetMethodNotAllowed) String() string {
	return fmt.Sprintf("[POST /pet][%d] addPetMethodNotAllowed", 405)
}

func (o *AddPetMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
