// Code generated by go-swagger; DO NOT EDIT.

package pet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"swaggerpet/api/models"
)

// FindPetsByStatusReader is a Reader for the FindPetsByStatus structure.
type FindPetsByStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FindPetsByStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFindPetsByStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewFindPetsByStatusBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /pet/findByStatus] findPetsByStatus", response, response.Code())
	}
}

// NewFindPetsByStatusOK creates a FindPetsByStatusOK with default headers values
func NewFindPetsByStatusOK() *FindPetsByStatusOK {
	return &FindPetsByStatusOK{}
}

/*
FindPetsByStatusOK describes a response with status code 200, with default header values.

successful operation
*/
type FindPetsByStatusOK struct {
	Payload []*models.Pet
}

// IsSuccess returns true when this find pets by status o k response has a 2xx status code
func (o *FindPetsByStatusOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this find pets by status o k response has a 3xx status code
func (o *FindPetsByStatusOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this find pets by status o k response has a 4xx status code
func (o *FindPetsByStatusOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this find pets by status o k response has a 5xx status code
func (o *FindPetsByStatusOK) IsServerError() bool {
	return false
}

// IsCode returns true when this find pets by status o k response a status code equal to that given
func (o *FindPetsByStatusOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the find pets by status o k response
func (o *FindPetsByStatusOK) Code() int {
	return 200
}

func (o *FindPetsByStatusOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /pet/findByStatus][%d] findPetsByStatusOK %s", 200, payload)
}

func (o *FindPetsByStatusOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /pet/findByStatus][%d] findPetsByStatusOK %s", 200, payload)
}

func (o *FindPetsByStatusOK) GetPayload() []*models.Pet {
	return o.Payload
}

func (o *FindPetsByStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewFindPetsByStatusBadRequest creates a FindPetsByStatusBadRequest with default headers values
func NewFindPetsByStatusBadRequest() *FindPetsByStatusBadRequest {
	return &FindPetsByStatusBadRequest{}
}

/*
FindPetsByStatusBadRequest describes a response with status code 400, with default header values.

Invalid status value
*/
type FindPetsByStatusBadRequest struct {
}

// IsSuccess returns true when this find pets by status bad request response has a 2xx status code
func (o *FindPetsByStatusBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this find pets by status bad request response has a 3xx status code
func (o *FindPetsByStatusBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this find pets by status bad request response has a 4xx status code
func (o *FindPetsByStatusBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this find pets by status bad request response has a 5xx status code
func (o *FindPetsByStatusBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this find pets by status bad request response a status code equal to that given
func (o *FindPetsByStatusBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the find pets by status bad request response
func (o *FindPetsByStatusBadRequest) Code() int {
	return 400
}

func (o *FindPetsByStatusBadRequest) Error() string {
	return fmt.Sprintf("[GET /pet/findByStatus][%d] findPetsByStatusBadRequest", 400)
}

func (o *FindPetsByStatusBadRequest) String() string {
	return fmt.Sprintf("[GET /pet/findByStatus][%d] findPetsByStatusBadRequest", 400)
}

func (o *FindPetsByStatusBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
