// Code generated by go-swagger; DO NOT EDIT.

package pet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UpdatePetReader is a Reader for the UpdatePet structure.
type UpdatePetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdatePetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 400:
		result := NewUpdatePetBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdatePetNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 405:
		result := NewUpdatePetMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /pet] updatePet", response, response.Code())
	}
}

// NewUpdatePetBadRequest creates a UpdatePetBadRequest with default headers values
func NewUpdatePetBadRequest() *UpdatePetBadRequest {
	return &UpdatePetBadRequest{}
}

/*
UpdatePetBadRequest describes a response with status code 400, with default header values.

Invalid ID supplied
*/
type UpdatePetBadRequest struct {
}

// IsSuccess returns true when this update pet bad request response has a 2xx status code
func (o *UpdatePetBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update pet bad request response has a 3xx status code
func (o *UpdatePetBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update pet bad request response has a 4xx status code
func (o *UpdatePetBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this update pet bad request response has a 5xx status code
func (o *UpdatePetBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this update pet bad request response a status code equal to that given
func (o *UpdatePetBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the update pet bad request response
func (o *UpdatePetBadRequest) Code() int {
	return 400
}

func (o *UpdatePetBadRequest) Error() string {
	return fmt.Sprintf("[PUT /pet][%d] updatePetBadRequest", 400)
}

func (o *UpdatePetBadRequest) String() string {
	return fmt.Sprintf("[PUT /pet][%d] updatePetBadRequest", 400)
}

func (o *UpdatePetBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdatePetNotFound creates a UpdatePetNotFound with default headers values
func NewUpdatePetNotFound() *UpdatePetNotFound {
	return &UpdatePetNotFound{}
}

/*
UpdatePetNotFound describes a response with status code 404, with default header values.

Pet not found
*/
type UpdatePetNotFound struct {
}

// IsSuccess returns true when this update pet not found response has a 2xx status code
func (o *UpdatePetNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update pet not found response has a 3xx status code
func (o *UpdatePetNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update pet not found response has a 4xx status code
func (o *UpdatePetNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this update pet not found response has a 5xx status code
func (o *UpdatePetNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this update pet not found response a status code equal to that given
func (o *UpdatePetNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the update pet not found response
func (o *UpdatePetNotFound) Code() int {
	return 404
}

func (o *UpdatePetNotFound) Error() string {
	return fmt.Sprintf("[PUT /pet][%d] updatePetNotFound", 404)
}

func (o *UpdatePetNotFound) String() string {
	return fmt.Sprintf("[PUT /pet][%d] updatePetNotFound", 404)
}

func (o *UpdatePetNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdatePetMethodNotAllowed creates a UpdatePetMethodNotAllowed with default headers values
func NewUpdatePetMethodNotAllowed() *UpdatePetMethodNotAllowed {
	return &UpdatePetMethodNotAllowed{}
}

/*
UpdatePetMethodNotAllowed describes a response with status code 405, with default header values.

Validation exception
*/
type UpdatePetMethodNotAllowed struct {
}

// IsSuccess returns true when this update pet method not allowed response has a 2xx status code
func (o *UpdatePetMethodNotAllowed) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update pet method not allowed response has a 3xx status code
func (o *UpdatePetMethodNotAllowed) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update pet method not allowed response has a 4xx status code
func (o *UpdatePetMethodNotAllowed) IsClientError() bool {
	return true
}

// IsServerError returns true when this update pet method not allowed response has a 5xx status code
func (o *UpdatePetMethodNotAllowed) IsServerError() bool {
	return false
}

// IsCode returns true when this update pet method not allowed response a status code equal to that given
func (o *UpdatePetMethodNotAllowed) IsCode(code int) bool {
	return code == 405
}

// Code gets the status code for the update pet method not allowed response
func (o *UpdatePetMethodNotAllowed) Code() int {
	return 405
}

func (o *UpdatePetMethodNotAllowed) Error() string {
	return fmt.Sprintf("[PUT /pet][%d] updatePetMethodNotAllowed", 405)
}

func (o *UpdatePetMethodNotAllowed) String() string {
	return fmt.Sprintf("[PUT /pet][%d] updatePetMethodNotAllowed", 405)
}

func (o *UpdatePetMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
