// Code generated by go-swagger; DO NOT EDIT.

package store

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"swaggerpet/api/models"
)

// GetOrderByIDReader is a Reader for the GetOrderByID structure.
type GetOrderByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOrderByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOrderByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetOrderByIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetOrderByIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /store/order/{orderId}] getOrderById", response, response.Code())
	}
}

// NewGetOrderByIDOK creates a GetOrderByIDOK with default headers values
func NewGetOrderByIDOK() *GetOrderByIDOK {
	return &GetOrderByIDOK{}
}

/*
GetOrderByIDOK describes a response with status code 200, with default header values.

successful operation
*/
type GetOrderByIDOK struct {
	Payload *models.Order
}

// IsSuccess returns true when this get order by Id o k response has a 2xx status code
func (o *GetOrderByIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get order by Id o k response has a 3xx status code
func (o *GetOrderByIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get order by Id o k response has a 4xx status code
func (o *GetOrderByIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get order by Id o k response has a 5xx status code
func (o *GetOrderByIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get order by Id o k response a status code equal to that given
func (o *GetOrderByIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get order by Id o k response
func (o *GetOrderByIDOK) Code() int {
	return 200
}

func (o *GetOrderByIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /store/order/{orderId}][%d] getOrderByIdOK %s", 200, payload)
}

func (o *GetOrderByIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /store/order/{orderId}][%d] getOrderByIdOK %s", 200, payload)
}

func (o *GetOrderByIDOK) GetPayload() *models.Order {
	return o.Payload
}

func (o *GetOrderByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Order)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOrderByIDBadRequest creates a GetOrderByIDBadRequest with default headers values
func NewGetOrderByIDBadRequest() *GetOrderByIDBadRequest {
	return &GetOrderByIDBadRequest{}
}

/*
GetOrderByIDBadRequest describes a response with status code 400, with default header values.

Invalid ID supplied
*/
type GetOrderByIDBadRequest struct {
}

// IsSuccess returns true when this get order by Id bad request response has a 2xx status code
func (o *GetOrderByIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get order by Id bad request response has a 3xx status code
func (o *GetOrderByIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get order by Id bad request response has a 4xx status code
func (o *GetOrderByIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get order by Id bad request response has a 5xx status code
func (o *GetOrderByIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get order by Id bad request response a status code equal to that given
func (o *GetOrderByIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get order by Id bad request response
func (o *GetOrderByIDBadRequest) Code() int {
	return 400
}

func (o *GetOrderByIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /store/order/{orderId}][%d] getOrderByIdBadRequest", 400)
}

func (o *GetOrderByIDBadRequest) String() string {
	return fmt.Sprintf("[GET /store/order/{orderId}][%d] getOrderByIdBadRequest", 400)
}

func (o *GetOrderByIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetOrderByIDNotFound creates a GetOrderByIDNotFound with default headers values
func NewGetOrderByIDNotFound() *GetOrderByIDNotFound {
	return &GetOrderByIDNotFound{}
}

/*
GetOrderByIDNotFound describes a response with status code 404, with default header values.

Order not found
*/
type GetOrderByIDNotFound struct {
}

// IsSuccess returns true when this get order by Id not found response has a 2xx status code
func (o *GetOrderByIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get order by Id not found response has a 3xx status code
func (o *GetOrderByIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get order by Id not found response has a 4xx status code
func (o *GetOrderByIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get order by Id not found response has a 5xx status code
func (o *GetOrderByIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get order by Id not found response a status code equal to that given
func (o *GetOrderByIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get order by Id not found response
func (o *GetOrderByIDNotFound) Code() int {
	return 404
}

func (o *GetOrderByIDNotFound) Error() string {
	return fmt.Sprintf("[GET /store/order/{orderId}][%d] getOrderByIdNotFound", 404)
}

func (o *GetOrderByIDNotFound) String() string {
	return fmt.Sprintf("[GET /store/order/{orderId}][%d] getOrderByIdNotFound", 404)
}

func (o *GetOrderByIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
