// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"swaggerpet/api/models"
)

// GetUserByNameReader is a Reader for the GetUserByName structure.
type GetUserByNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetUserByNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetUserByNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetUserByNameBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetUserByNameNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /user/{username}] getUserByName", response, response.Code())
	}
}

// NewGetUserByNameOK creates a GetUserByNameOK with default headers values
func NewGetUserByNameOK() *GetUserByNameOK {
	return &GetUserByNameOK{}
}

/*
GetUserByNameOK describes a response with status code 200, with default header values.

successful operation
*/
type GetUserByNameOK struct {
	Payload *models.User
}

// IsSuccess returns true when this get user by name o k response has a 2xx status code
func (o *GetUserByNameOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get user by name o k response has a 3xx status code
func (o *GetUserByNameOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get user by name o k response has a 4xx status code
func (o *GetUserByNameOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get user by name o k response has a 5xx status code
func (o *GetUserByNameOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get user by name o k response a status code equal to that given
func (o *GetUserByNameOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get user by name o k response
func (o *GetUserByNameOK) Code() int {
	return 200
}

func (o *GetUserByNameOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /user/{username}][%d] getUserByNameOK %s", 200, payload)
}

func (o *GetUserByNameOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /user/{username}][%d] getUserByNameOK %s", 200, payload)
}

func (o *GetUserByNameOK) GetPayload() *models.User {
	return o.Payload
}

func (o *GetUserByNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.User)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUserByNameBadRequest creates a GetUserByNameBadRequest with default headers values
func NewGetUserByNameBadRequest() *GetUserByNameBadRequest {
	return &GetUserByNameBadRequest{}
}

/*
GetUserByNameBadRequest describes a response with status code 400, with default header values.

Invalid username supplied
*/
type GetUserByNameBadRequest struct {
}

// IsSuccess returns true when this get user by name bad request response has a 2xx status code
func (o *GetUserByNameBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get user by name bad request response has a 3xx status code
func (o *GetUserByNameBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get user by name bad request response has a 4xx status code
func (o *GetUserByNameBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get user by name bad request response has a 5xx status code
func (o *GetUserByNameBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get user by name bad request response a status code equal to that given
func (o *GetUserByNameBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get user by name bad request response
func (o *GetUserByNameBadRequest) Code() int {
	return 400
}

func (o *GetUserByNameBadRequest) Error() string {
	return fmt.Sprintf("[GET /user/{username}][%d] getUserByNameBadRequest", 400)
}

func (o *GetUserByNameBadRequest) String() string {
	return fmt.Sprintf("[GET /user/{username}][%d] getUserByNameBadRequest", 400)
}

func (o *GetUserByNameBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetUserByNameNotFound creates a GetUserByNameNotFound with default headers values
func NewGetUserByNameNotFound() *GetUserByNameNotFound {
	return &GetUserByNameNotFound{}
}

/*
GetUserByNameNotFound describes a response with status code 404, with default header values.

User not found
*/
type GetUserByNameNotFound struct {
}

// IsSuccess returns true when this get user by name not found response has a 2xx status code
func (o *GetUserByNameNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get user by name not found response has a 3xx status code
func (o *GetUserByNameNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get user by name not found response has a 4xx status code
func (o *GetUserByNameNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get user by name not found response has a 5xx status code
func (o *GetUserByNameNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get user by name not found response a status code equal to that given
func (o *GetUserByNameNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get user by name not found response
func (o *GetUserByNameNotFound) Code() int {
	return 404
}

func (o *GetUserByNameNotFound) Error() string {
	return fmt.Sprintf("[GET /user/{username}][%d] getUserByNameNotFound", 404)
}

func (o *GetUserByNameNotFound) String() string {
	return fmt.Sprintf("[GET /user/{username}][%d] getUserByNameNotFound", 404)
}

func (o *GetUserByNameNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
