// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LoginUserReader is a Reader for the LoginUser structure.
type LoginUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LoginUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLoginUserOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewLoginUserBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /user/login] loginUser", response, response.Code())
	}
}

// NewLoginUserOK creates a LoginUserOK with default headers values
func NewLoginUserOK() *LoginUserOK {
	return &LoginUserOK{}
}

/*
LoginUserOK describes a response with status code 200, with default header values.

successful operation
*/
type LoginUserOK struct {

	/* date in UTC when token expires

	   Format: date-time
	*/
	XExpiresAfter strfmt.DateTime

	/* calls per hour allowed by the user

	   Format: int32
	*/
	XRateLimit int32

	Payload string
}

// IsSuccess returns true when this login user o k response has a 2xx status code
func (o *LoginUserOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this login user o k response has a 3xx status code
func (o *LoginUserOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this login user o k response has a 4xx status code
func (o *LoginUserOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this login user o k response has a 5xx status code
func (o *LoginUserOK) IsServerError() bool {
	return false
}

// IsCode returns true when this login user o k response a status code equal to that given
func (o *LoginUserOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the login user o k response
func (o *LoginUserOK) Code() int {
	return 200
}

func (o *LoginUserOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /user/login][%d] loginUserOK %s", 200, payload)
}

func (o *LoginUserOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /user/login][%d] loginUserOK %s", 200, payload)
}

func (o *LoginUserOK) GetPayload() string {
	return o.Payload
}

func (o *LoginUserOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Expires-After
	hdrXExpiresAfter := response.GetHeader("X-Expires-After")

	if hdrXExpiresAfter != "" {
		valxExpiresAfter, err := formats.Parse("date-time", hdrXExpiresAfter)
		if err != nil {
			return errors.InvalidType("X-Expires-After", "header", "strfmt.DateTime", hdrXExpiresAfter)
		}
		o.XExpiresAfter = *(valxExpiresAfter.(*strfmt.DateTime))
	}

	// hydrates response header X-Rate-Limit
	hdrXRateLimit := response.GetHeader("X-Rate-Limit")

	if hdrXRateLimit != "" {
		valxRateLimit, err := swag.ConvertInt32(hdrXRateLimit)
		if err != nil {
			return errors.InvalidType("X-Rate-Limit", "header", "int32", hdrXRateLimit)
		}
		o.XRateLimit = valxRateLimit
	}

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLoginUserBadRequest creates a LoginUserBadRequest with default headers values
func NewLoginUserBadRequest() *LoginUserBadRequest {
	return &LoginUserBadRequest{}
}

/*
LoginUserBadRequest describes a response with status code 400, with default header values.

Invalid username/password supplied
*/
type LoginUserBadRequest struct {
}

// IsSuccess returns true when this login user bad request response has a 2xx status code
func (o *LoginUserBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this login user bad request response has a 3xx status code
func (o *LoginUserBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this login user bad request response has a 4xx status code
func (o *LoginUserBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this login user bad request response has a 5xx status code
func (o *LoginUserBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this login user bad request response a status code equal to that given
func (o *LoginUserBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the login user bad request response
func (o *LoginUserBadRequest) Code() int {
	return 400
}

func (o *LoginUserBadRequest) Error() string {
	return fmt.Sprintf("[GET /user/login][%d] loginUserBadRequest", 400)
}

func (o *LoginUserBadRequest) String() string {
	return fmt.Sprintf("[GET /user/login][%d] loginUserBadRequest", 400)
}

func (o *LoginUserBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
