// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// LogoutUserReader is a Reader for the LogoutUser structure.
type LogoutUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LogoutUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewLogoutUserDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewLogoutUserDefault creates a LogoutUserDefault with default headers values
func NewLogoutUserDefault(code int) *LogoutUserDefault {
	return &LogoutUserDefault{
		_statusCode: code,
	}
}

/*
LogoutUserDefault describes a response with status code -1, with default header values.

successful operation
*/
type LogoutUserDefault struct {
	_statusCode int
}

// IsSuccess returns true when this logout user default response has a 2xx status code
func (o *LogoutUserDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this logout user default response has a 3xx status code
func (o *LogoutUserDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this logout user default response has a 4xx status code
func (o *LogoutUserDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this logout user default response has a 5xx status code
func (o *LogoutUserDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this logout user default response a status code equal to that given
func (o *LogoutUserDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the logout user default response
func (o *LogoutUserDefault) Code() int {
	return o._statusCode
}

func (o *LogoutUserDefault) Error() string {
	return fmt.Sprintf("[GET /user/logout][%d] logoutUser default", o._statusCode)
}

func (o *LogoutUserDefault) String() string {
	return fmt.Sprintf("[GET /user/logout][%d] logoutUser default", o._statusCode)
}

func (o *LogoutUserDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
